name: juicer-to-deeploop
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:

  - python=3.7
  - pip
  - openjdk  
  - parallel
  - make
  - java-jdk
  - gcc
  - coreutils
  - pigz
  - curl